# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2993e31e71939664b4f6a255d27d6ab4"
name = "ShopBrain AI"
application_url = "https://shopbrain-backend.onrender.com/api/shopify/install"
embedded = false
handle = "shopbrain-ai-louis-felix"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://shopbrain-backend.onrender.com/api/shopify/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://shopbrain-backend.onrender.com/api/shopify/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://shopbrain-backend.onrender.com/api/shopify/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_orders,read_products,read_script_tags,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shopbrain-backend.onrender.com/auth/shopify/callback"
]
